### ISSUE TITLE
 Error installing

### ISSUE THREAD

**Issue by gumazza** [avollkopf/cbpi4_GroupedSensor#3]
I'm trying to install and I'm getting the following error:

ERROR: Could not find a version that satisfies the requirement cbpi4_GroupedSensor
ERROR: No matching distribution found for cbpi4_GroupedSensor

**Comment by avollkopf** [comment]
How did you try to install the plugin? Via pypi or from the repo?

I need to update the README anyhow since 'avollkopf' needs to be replaced with 'PiBrewing'

**Comment by avollkopf** [comment]
Somehow, package has never been uploaded to pypi. [Fixed now](https://pypi.org/project/cbpi4-GroupedSensor/)
